version: "3.7"
services:
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/volume/data/:/var/lib/rabbitmq
      - ./rabbitmq/volume/log/:/var/log/rabbitmq

  mongodb:
    container_name: MongoDB
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: steve
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/volume/data/:/data/db/